---
title: "03_describe"
format: html
editor: visual
---

## Loading necessary packages

```{r}
instal.packages("ggplot2")
library(ggplot2)
```

## Describing the data

Summary of basic statistics for ASCO, SCC and metaData:

```{r}
summary(ASCO_clean)
summary(SCC_clean)
summary(metaData)
```

## Visualization of the distribution for SIFT and PolyPhen scores

```{r}
# Histogram for SIFT scores
ggplot(ASCO_clean, aes(x=SIFT_Score)) + geom_histogram()

# Histogram for PolyPhen scores
ggplot(ASCO_clean, aes(x=PolyPhen_Score)) + geom_histogram()
```

## Dimension of data

```{r}
dim(ASCO_clean)
dim(SCC_clean)
```

## Outliers

```{r}
# Selecting the relevant columns and then combining the data
ASCO_long <- ASCO_clean %>% 
  select(Affected_Num_Cohort, Total_Num_Cohort, Percentage_Cohort, Affected_GDC, 
         Total_GDC, SIFT_Score, PolyPhen_Score) %>% 
  gather(key="variable", value="value") %>% 
  mutate(dataset="ASCO")

SCC_long <- SCC_clean %>% 
  select(Affected_Num_Cohort, Total_Num_Cohort, Percentage_Cohort, Affected_GDC, 
         Total_GDC, SIFT_Score, PolyPhen_Score) %>% 
  gather(key="variable", value="value") %>% 
  mutate(dataset="SCC")

combined_data <- bind_rows(ASCO_long, SCC_long)

# Boxplot
boxplot <- ggplot(combined_data, aes(x=dataset, y=value, fill=dataset)) + 
  geom_boxplot(outlier.colour="red", outlier.shape=1, outlier.size=2) +
  facet_wrap(~variable, scales="free") + 
  labs(title="Boxplot of Variables") +
  theme_minimal()


# Calculate outlier boundaries for each variable
outlier_bounds <- combined_data %>%
  group_by(variable, dataset) %>%
  summarise(upper = quantile(value, 0.75, na.rm=TRUE) + 1.5 * IQR(value, na.rm=TRUE),
            lower = quantile(value, 0.25, na.rm=TRUE) - 1.5 * IQR(value, na.rm=TRUE))

combined_data <- merge(combined_data, outlier_bounds)

# Plot
boxplot <- ggplot(combined_data, aes(x=dataset, y=value, fill=dataset)) + 
  geom_boxplot(outlier.colour="red", outlier.shape=1, outlier.size=2) +
  
  # Label the outliers
  # geom_text(aes(label=ifelse(value > upper | value < lower, round(value,2), NA)), 
            #vjust=1.5, color="black", size=3) +
  
  # Improve boxplot color
  scale_fill_manual(values=c("ASCO"="#E57373", "SCC"="#81C784")) +
  
  # Enhance axis titles
  labs(title="Comparison of Variables", x="", y="Value") +
  
  # Increase size of axis text & title
  theme_minimal() +
  theme(axis.title.x=element_text(size=14, face="bold"),
        axis.title.y=element_text(size=14, face="bold"),
        axis.text.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        plot.title=element_text(size=16, face="bold", hjust=0.5),
        legend.title=element_blank(),
        legend.text=element_text(size=12)) +
  
  # Reordering the facet by median
  facet_wrap(~reorder(variable, value, FUN=median), scales="free_y") 
```
