---
title: "04_augment"
format: html
editor: visual
---

## Loading packages

```{r}
library(tidyverse)
```

## Creating a function to categorizing the consequence column

```{r}
# Define the function
categorize_consequences <- function(consequence) {
  if (grepl("^Missense", consequence)) {
    return("Missense")
  } else if (grepl("^Frameshift", consequence)) {
    return("Frameshift")
  } else if (grepl("^Inframe Deletion", consequence)) {
    return("Inframe Deletion")
  } else if (grepl("^Stop Gained", consequence)) {
    return("Stop Gained")
  } else if (grepl("^Splice", consequence)) {
    return("Splice")
  } else if (grepl("^Inframe Insertion", consequence)) {
    return("Inframe Insertion")
  } else if (grepl("^Synonymous", consequence)) {
    return("Synonymous")
  } else if (grepl("^Start Lost", consequence)) {
    return("Start Lost")
  } else {
    return("Other")
  }
}

# Apply the function using mutate and map_chr from the tidyverse

# For ASCO
ASCO_clean <- ASCO_clean %>%
  mutate(Category = map_chr(Consequences, categorize_consequences))

# For SCC
SCC_clean <- SCC_clean %>%
  mutate(Category = map_chr(Consequences, categorize_consequences))
```

## Count mutations and visualize

By type:

```{r}
ASCO_clean %>% count(Type)
SCC_clean %>% count(Type)
```

```{r}
ASCO_clean %>%
  group_by(Type) %>%
  summarize(count = n()) %>%
  ggplot(aes(x=Type, y=count)) + 
  geom_bar(stat='identity')

SCC_clean %>%
  group_by(Type) %>%
  summarize(count = n()) %>%
  ggplot(aes(x=Type, y=count)) + 
  geom_bar(stat='identity')
```

By category:

```{r}
ASCO_clean %>% count(Category)
SCC_clean %>% count(Category)
```

```{r}
ASCO_clean %>%
  group_by(Category) %>%
  summarize(count = n()) %>%
  ggplot(aes(x=Category, y=count)) + 
  geom_bar(stat='identity')

SCC_clean %>%
  group_by(Category) %>%
  summarize(count = n()) %>%
  ggplot(aes(x=Category, y=count)) + 
  geom_bar(stat='identity')
```

## Saving data

```{r}
write.csv(ASCO_clean, "~/project29_git/_raw/data/04_aug_ASCO.tsv", row.names = FALSE)
write.csv(SCC_clean, "~/project29_git/_raw/data/04_aug_SCC.tsv", row.names = FALSE)
```
